### ISSUE TITLE
Lỗi biên dịch trên linux file header arduino.h viết thường

### ISSUE THREAD

**Issue by huyngo1122** [devshop2019/MachTestHangDaNang#1]
- biên dịch lỗi file arduino.h không chạy được trên linux

+ sửa tên file arduino.h ->> Arduino.h 
--/-/-/-/-/-/

**Comment by devshop2019** [comment]
Đã Fix Arduino.h trên Linux
https://github.com/devshop2019/MachTestHangDaNang/commit/332f49a98f7382f6d5eeb42081e9d724d9d3540f
